apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: sounj142/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*'
            dest: .

    - image: sounj142/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*'
            dest: .

    - image: sounj142/client-normal-react
      context: client-normal-react
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts*'
            dest: .
          - src: '**/*.html'
            dest: .
          - src: '**/*.css'
            dest: .
            