apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-srv
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: ticketing-server-app.vn
      http:
        paths:
        - path: /api/users/
          pathType: Prefix
          backend:
            service:
              name: auth-srv
              port:
                number: 3000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-srv
              port:
                number: 3000



    - host: ticketing-client-app.vn
      http:
        paths:
        - path: /api/users/
          pathType: Prefix
          backend:
            service:
              name: auth-srv
              port:
                number: 3000
        - path: /
          pathType: Prefix
          backend:
            service:
              name: client-normal-react-srv
              port:
                number: 3000

